# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Test
  jobs:
  - job: init
    displayName: 'Initialization'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      displayName: 'Terraform Install'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Azure for Students(3616b9f9-5e04-488f-87ac-d012d9d36a69)'
        backendAzureRmResourceGroupName: 'storage'
        backendAzureRmStorageAccountName: 'liubfiles'
        backendAzureRmContainerName: 'bestrong-tfstate'
        backendAzureRmKey: 'devops'
      displayName: 'Terraform Init'
  # - job: check
  #   displayName: 'Check'
  #   steps:
    - task: TerraformTaskV4@4
      displayName: 'Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'


  # - job: deploy
  #   displayName: 'Validation'
  #   dependsOn: init
  #   steps:


